import { v4 as uuid } from "uuid";

export const DashboardMenu = [
  {
    id: uuid(),
    title: "Dashboard",
    icon: "home",
    link: "/management/dashboard",
    role: ["super-admin", "admin", "user", "super-admin"],
  },
        {
    id: uuid(),
    title: "Patient",
    icon: "home",
    link: "/management/dashboard/patients",
    role: ["super-admin", "admin", "user", "super-admin"],
  },
  {
    id: uuid(),
    title: "Services",
    icon: "home",
    link: "/management/dashboard/services",
    role: ["super-admin", "admin", "user", "super-admin"],
  },
    {
    id: uuid(),
    title: "Diseases",
    icon: "home",
    link: "/management/dashboard/diseases",
    role: ["super-admin", "admin", "user", "super-admin"],
  },
    {
    id: uuid(),
    title: "Whatsapp Marketing",
    icon: "home",
    link: "/management/dashboard/whatsapp-marketing",
    role: ["super-admin", "admin", "user", "super-admin"],
  },
    {
    id: uuid(),
    title: "SMS Marketing",
    icon: "home",
    link: "/management/dashboard/sms-marketing",
    role: ["super-admin", "admin", "user", "super-admin"],
  },
    {
    id: uuid(),
    title: "Email Marketing",
    icon: "home",
    link: "/management/dashboard/email-marketing",
    role: ["super-admin", "admin", "user", "super-admin"],
  },
  // {
  //   id: uuid(),
  //   title: "Configurations",
  //   icon: "monitor",
  //   role: ["admin", "super-admin"],
  //   children: [
  //     {
  //       id: uuid(),
  //       link: "/management/dashboard/organization",
  //       name: "Organization",
  //       icon: "users",
  //       role: ["super-admin"],
  //     },
  //     {
  //       id: uuid(),
  //       link: "/management/dashboard/department",
  //       name: "Department",
  //       icon: "layers",
  //       role: ["admin", "super-admin"],
  //     },
  //     {
  //       id: uuid(),
  //       link: "/management/dashboard/department_head",
  //       name: "Department_Head",
  //       icon: "layers",
  //       role: ["admin", "super-admin"],
  //     },
  //     {
  //       id: uuid(),
  //       link: "/management/dashboard/designation",
  //       name: "Designation",
  //       icon: "briefcase",
  //       role: ["admin", "super-admin"],
  //     },
  //     {
  //       id: uuid(),
  //       link: "/management/dashboard/performance-indicator",
  //       name: "KPIs",
  //       icon: "sun",
  //       role: ["admin", "super-admin"],
  //     },
  //     {
  //       id: uuid(),
  //       link: "/management/dashboard/allowances",
  //       name: "Allowances",
  //       icon: "sun",
  //       role: ["admin", "super-admin"],
  //     },
  //     {
  //       id: uuid(),
  //       link: "/management/dashboard/deduction",
  //       name: "Deduction",
  //       icon: "sun",
  //       role: ["admin", "super-admin"],
  //     },
  //     {
  //       id: uuid(),
  //       link: "/management/dashboard/offer_letter",
  //       name: "Offer Letter",
  //       icon: "sun",
  //       role: ["admin", "super-admin"],
  //     },
  //     {
  //       id: uuid(),
  //       link: "/management/dashboard/announcement",
  //       name: "Announcement",
  //       icon: "sun",
  //       role: ["admin", "super-admin"],
  //     },
  //     {
  //       id: uuid(),
  //       link: "/management/dashboard/training",
  //       name: "Training",
  //       icon: "sun",
  //       role: ["admin", "super-admin"],
  //     },
  //     {
  //       id: uuid(),
  //       link: "/management/dashboard/emp_exit",
  //       name: "Emp Exit",
  //       icon: "sun",
  //       role: ["admin", "super-admin"],
  //     },
  //   ],
  // },
  // 👇 Leave Management moved here
  // {
  //   id: uuid(),
  //   title: "Leave Management",
  //   icon: "calendar",
  //   role: ["admin", "super-admin"],
  //   children: [
  //     {
  //       id: uuid(),
  //       link: "/management/dashboard/holidays",
  //       name: "Holidays",
  //       icon: "sun",
  //       role: ["admin", "super-admin"],
  //     },
  //     {
  //       id: uuid(),
  //       link: "/management/dashboard/leave",
  //       name: "Leave Type",
  //       icon: "calendar",
  //       role: ["admin", "super-admin"],
  //     }
  //   ],
  // },
  // {
  //   id: uuid(),
  //   title: "Emp Management",
  //   icon: "calendar",
  //   role: ["admin", "super-admin"],
  //   children: [
  //           {
  //       id: uuid(),
  //       link: "/management/dashboard/employee_type",
  //       name: "Employee Type",
  //       icon: "sun",
  //       role: ["admin", "super-admin"],
  //     },
  //     {
  //       id: uuid(),
  //       link: "/management/dashboard/intent_form",
  //       name: "Intent Users",
  //       icon: "sun",
  //       role: ["admin", "super-admin"],
  //     },
  //     {
  //       id: uuid(),
  //       name: "Employees",
  //       icon: "users",
  //       link: "/management/dashboard/employees",
  //       role: ["admin", "user", "super-admin"],
  //     },
  //     {
  //       id: uuid(),
  //       name: "Onboarding",
  //       icon: "file-text",
  //       link: "/management/dashboard/onboarding",
  //       role: ["admin", "super-admin"],
  //     },
  //     {
  //       name: "Performance",
  //       icon: "clipboard",
  //       link: "/management/dashboard/performance",
  //       role: ["admin", "super-admin", "user"],
  //     },
  //   ],
  // },
  // {
  //   id: uuid(),
  //   title: "Policies",
  //   icon: "clipboard",
  //   link: "/management/dashboard/policies",
  //   role: ["admin", "user", "super-admin"],
  // },
  // {
  //   id: uuid(),
  //   title: "Profile",
  //   link: "/management/dashboard/profile",
  //   icon: "user",
  //   role: ["user", "super-admin"],
  // },
  // {
  //   id: uuid(),
  //   title: "Attendance",
  //   icon: "check-square",
  //   link: "/management/dashboard/attendance",
  //   role: ["admin", "super-admin"],
  // },
  // {
  //   id: uuid(),
  //   title: "Leave Request",
  //   icon: "file-text",
  //   link: "/management/dashboard/leave-form",
  //   role: ["admin", "user", "super-admin"],
  // },
  // {
  //   id: uuid(),
  //   title: "Leave Reports",
  //   icon: "clipboard",
  //   link: "/management/dashboard/leave-application-employee",
  //   role: ["admin", "super-admin"],
  // },
  // {
  //   id: uuid(),
  //   title: "Calendar",
  //   icon: "calendar",
  //   link: "/management/dashboard/org-calendar",
  //   role: ["admin", "user", "super-admin"],
  // },
  // {
  //   title: "Monthly Salary",
  //   icon: "clipboard",
  //   link: "/management/dashboard/monthly-employees-salary",
  //   role: ["user", "admin", "super-admin"],
  // },
  // {
  //   title: "PaySlips",
  //   icon: "clipboard",
  //   link: "/management/dashboard/payslip-management",
  //   role: ["admin", "super-admin"],
  // },
];

export default DashboardMenu;

      //   children: [
      //           {
      //       id: uuid(),
      //       link: "/management/dashboard/intent_form",
      //       name: "Intent Users",
      //       icon: "sun",
      //       role: ["admin", "super-admin"],
      //     },
      //     {
      //       id: uuid(),
      //       name: "Employees",
      //       icon: "users",
      //       link: "/management/dashboard/employees",
      //       role: ["admin", "user", "super-admin"],
      //     },
      //     {
      //       id: uuid(),
      //       name: "EMP Salary",
      //       icon: "clipboard",
      //       link: "/management/dashboard/emp_salary",
      //       role: ["admin", "super-admin"],
      //     },
      //       {
      //       id: uuid(),
      //       name: "Onboarding",
      //       icon: "file-text",
      //       link: "/management/dashboard/onboarding",
      //       role: ["admin", "super-admin"],
      //     },
      //       {
      //       name: "Performance",
      //       icon: "clipboard",
      //       link: "/management/dashboard/performance",
      //       role: ["admin", "super-admin", "user"],
      //     },
      //   ],
      // },